apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastboopmos
configurations:
  - kustomizeconfig.yaml
resources:
  - certificate.yaml
  - gitrepo.yaml
  - release-secret.yaml
  - httproute.yaml
  - workload-deployment.yaml
  - tofu.yaml
  - tofu-env.yaml
configMapGenerator:
  - name: fastboopmos-frontdoor-config
    literals:
      - CACHE_DIR=/cache
      - GITHUB_OWNER=samcday
      - GITHUB_REPO=fastboopmos
      - ASSET_NAME=edge.channel
      - SHA256_ASSET_NAME=edge.channel.sha256
      - MAX_DOWNLOAD_BYTES=1073741824
    files:
      - EDGE_CHANNEL_ARTIFACT_ID=latest.txt
