apiVersion: v1
kind: Secret
metadata:
    name: fastboopmos-release
    namespace: fastboopmos
stringData:
    token: ENC[AES256_GCM,data:vIiWgcvvyltKF7PrMCUgds2ZN848qo4vzPWc927qNCxXBcqk9T8mGx8Hndke1p7ITlNlxdCmSoJKm7KEBFk/YbLpVS2i8MyVU2J4EzepFNHNEhrngfSkiPDj9nU0,iv:3Wsb6qnJGhbubChPLtJjWIrfhkfdZhE+h++OZ3QdVc8=,tag:3uxJ0u4KDNhVNo0pyzF3bw==,type:str]
sops:
    age:
        - recipient: age1utf3jfmexu3zsfqphejlh8ptx7av09jdh9n305jaqwa5s0nqevxsja4r76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkanFTaHFxeDlnRmlWbzZr
            YlBPN0xtNDRDRUgwd0pJYWtmVXZwQlZUTW1NCm9HalV0V2tVZmtOOTdVSzQvekxR
            V0dNYlJ5Q1V5aGhKTWl3c0YzZE82bUkKLS0tIDlaTTl3M0xORVVVZmtmNGZMcnVK
            KzY2dmtqSXRMT3IvMTdSRjU0cHd4ZncKYLMS7QvcFu/9hw8JC7EEGUKhHlyNBdyO
            6hr7IZ8LAewrV3Syw2GYUqTBBcZzeWCSthIIheoveOYgL2oF9mSnXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T12:54:36Z"
    mac: ENC[AES256_GCM,data:ONAEH91VO0ez6aKwdLaCXrkBamrc0AoTGpuSheH9JunIwAChG4d0J6/qbgSRo2K2KBjwb/A3VYeArd6PGZ6Y6+5vml6c5Gz7BQEBUwB3hSKfzuxFiaqAcLAMHhERoFqvj814Vt/QLuMqkIpzX4MEWP3l7vYyyWdNaFVCNg54hXU=,iv:eLVoQs4pHqBteALvbC+yHCNADq9efA4ARwTMnWXhcp4=,tag:mQVQRCu1T97wGwyU7QSC9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
