apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tofu
spec:
  interval: 30m
  approvePlan: auto
  path: ./infra/tofu
  sourceRef:
    kind: GitRepository
    name: fastboopmos
  destroyResourcesOnDeletion: false
  varsFrom:
    - kind: Secret
      name: tofu-bucket-vars
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: tofu-env
